namenode:
    image: gelog/hadoop
    ports:
        - "50070:50070"
        - "9000:9000"
        - "8020:8020"
        - "19888:19888"
        - "10020:10020"
    command: hdfs namenode
    hostname: hdfs-namenode

datanode:
    image: gelog/hadoop
    command: hdfs datanode
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
        - "50075"
        - "50020"
        - "50010"
    links:
        - namenode:hdfs-namenode

secondarynamenode:
    image: gelog/hadoop
    command: hdfs secondarynamenode
    ports:
        - "50090:50090"
    links:
        - namenode:hdfs-namenode
